spring.application.name=heracles-api
# ===============================
# BANCO DE DADOS (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/heracles_db
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
# validate: Garante que o Java não vai tentar criar ou apagar tabelas sozinho
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SEGURANÇA (JWT)
# ===============================
api.security.token.secret=sua_senha_super_secreta_heracles_2026